env path:   
mamba activate /Volumes/nimas_usb/Docs/envs/ssdbase

In [1]:
import os
import re
import pandas as pd
from pathlib import Path

AvanaRawReadcounts.csv:  Raw sgRNA read counts for all screens and pDNA baselines.  
AvanaGuideMap.csv:       Mapping between sgRNAs and their target genes.  
ScreenSequenceMap.csv:   Metadata for replicates: cell line, QC status, pDNA indicator.

In [2]:
# Mac Data Paths
raw   = pd.read_csv(os.path.expanduser("~/Google Drive/My Drive/informatics/AI projects/crispr_ai_ml/crispr-ml-hitcalling/data_raw/AvanaRawReadcounts.csv"))
guide = pd.read_csv(os.path.expanduser("~/Google Drive/My Drive/informatics/AI projects/crispr_ai_ml/crispr-ml-hitcalling/data_raw/AvanaGuideMap.csv"))
seqmap = pd.read_csv(os.path.expanduser("~/Google Drive/My Drive/informatics/AI projects/crispr_ai_ml/crispr-ml-hitcalling/data_raw/ScreenSequenceMap.csv"))

In [ ]:
# Linux Data Paths#
raw   = pd.read_csv(os.path.expanduser("~/Google Drive/informatics/AI projects/crispr_ai_ml/crispr-ml-hitcalling/data_raw/AvanaRawReadcounts.csv"))
guide = pd.read_csv(os.path.expanduser("~/Google Drive/informatics/AI projects/crispr_ai_ml/crispr-ml-hitcalling/data_raw/AvanaGuideMap.csv"))
seqmap = pd.read_csv(os.path.expanduser("~/Google Drive/informatics/AI projects/crispr_ai_ml/crispr-ml-hitcalling/data_raw/ScreenSequenceMap.csv"))

### Exploratory codes

In [3]:
raw.shape, guide.shape, seqmap.shape

((74687, 2285), (170429, 6), (3238, 12))

In [4]:
"""
raw.columns[-10:].tolist()
raw.columns[raw.columns.str.startswith('pDNA_batch')].tolist()
with open(os.path.expanduser("~/Google Drive/My Drive/informatics/AI projects/crispr_ai_ml/crispr-ml-hitcalling/notebooks/raw_columns.txt"), "w") as f:
    for col in raw.columns.tolist():
        f.write(col + "\n")
"""

'\nraw.columns[-10:].tolist()\nraw.columns[raw.columns.str.startswith(\'pDNA_batch\')].tolist()\nwith open(os.path.expanduser("~/Google Drive/My Drive/informatics/AI projects/crispr_ai_ml/crispr-ml-hitcalling/notebooks/raw_columns.txt"), "w") as f:\n    for col in raw.columns.tolist():\n        f.write(col + "\n")\n'

In [5]:
raw.head(3)

,Unnamed: 0,Colo699-311cas9-RepA-p6_Avana-4,Colo699-311cas9-RepB-p6_Avana-4,HSB-2-311cas9_RepA_p4_Avana-3,HSB-2-311cas9_RepB_p4_Avana-3,NCIH1339-311Cas9_RepA_p6_Avana-3,NCIH1339-311Cas9_RepB_p6_Avana-3,HEL-311Cas9_RepA_p4_Avana-3,HEL-311Cas9_RepB_p4_Avana-3,HEL9217-311Cas9_RepA_p6_Avana-3,...,HMMME-311cas9-RepB-p6_Avana-4,JVE528-311cas9-RepB-p6_Avana-4,UACC3133-311Cas9-RepB-P6_Avana-4,LU139-311cas9-RepB-p5_Avana-4,UPMM3-311cas9-RepA-p4_Avana-4,UACC3199-311cas9-RepA-p4_Avana-4,UACC3199-311cas9-RepB-p4_Avana-4,pDNA_batch_Avana-4,pDNA_batch_Avana-3,pDNA_batch_Avana-2
0,AAAAAAATCCAGCAATGCAG,463.0,521.0,514.0,776.0,474.0,329.0,214.0,254.0,510.0,...,450.0,471.0,460.0,419.0,275.0,528.0,546.0,2165.0,6327.0,190.5
1,AAAAAACCCGTAGATAGCCT,570.0,596.0,581.0,756.0,398.0,281.0,218.0,270.0,603.0,...,741.0,537.0,406.0,577.0,385.0,733.0,608.0,3127.5,9322.0,289.0
2,AAAAAAGAAGAAAAAACCAG,93.0,79.0,135.0,244.0,85.0,45.0,106.0,118.0,171.0,...,52.0,89.0,171.0,45.0,100.0,149.0,127.0,517.0,2030.5,41.5

In [6]:
raw.rename(columns={'Unnamed: 0': 'sgRNA_seq'}, inplace=True)
raw.head(3)

,sgRNA_seq,Colo699-311cas9-RepA-p6_Avana-4,Colo699-311cas9-RepB-p6_Avana-4,HSB-2-311cas9_RepA_p4_Avana-3,HSB-2-311cas9_RepB_p4_Avana-3,NCIH1339-311Cas9_RepA_p6_Avana-3,NCIH1339-311Cas9_RepB_p6_Avana-3,HEL-311Cas9_RepA_p4_Avana-3,HEL-311Cas9_RepB_p4_Avana-3,HEL9217-311Cas9_RepA_p6_Avana-3,...,HMMME-311cas9-RepB-p6_Avana-4,JVE528-311cas9-RepB-p6_Avana-4,UACC3133-311Cas9-RepB-P6_Avana-4,LU139-311cas9-RepB-p5_Avana-4,UPMM3-311cas9-RepA-p4_Avana-4,UACC3199-311cas9-RepA-p4_Avana-4,UACC3199-311cas9-RepB-p4_Avana-4,pDNA_batch_Avana-4,pDNA_batch_Avana-3,pDNA_batch_Avana-2
0,AAAAAAATCCAGCAATGCAG,463.0,521.0,514.0,776.0,474.0,329.0,214.0,254.0,510.0,...,450.0,471.0,460.0,419.0,275.0,528.0,546.0,2165.0,6327.0,190.5
1,AAAAAACCCGTAGATAGCCT,570.0,596.0,581.0,756.0,398.0,281.0,218.0,270.0,603.0,...,741.0,537.0,406.0,577.0,385.0,733.0,608.0,3127.5,9322.0,289.0
2,AAAAAAGAAGAAAAAACCAG,93.0,79.0,135.0,244.0,85.0,45.0,106.0,118.0,171.0,...,52.0,89.0,171.0,45.0,100.0,149.0,127.0,517.0,2030.5,41.5

In [7]:
print(raw.columns.to_list())

['sgRNA_seq', 'Colo699-311cas9-RepA-p6_Avana-4', 'Colo699-311cas9-RepB-p6_Avana-4', 'HSB-2-311cas9_RepA_p4_Avana-3', 'HSB-2-311cas9_RepB_p4_Avana-3', 'NCIH1339-311Cas9_RepA_p6_Avana-3', 'NCIH1339-311Cas9_RepB_p6_Avana-3', 'HEL-311Cas9_RepA_p4_Avana-3', 'HEL-311Cas9_RepB_p4_Avana-3', 'HEL9217-311Cas9_RepA_p6_Avana-3', 'HEL9217-311Cas9_RepB_p6_Avana-3', 'LS513-311Cas9_RepA_p6_Avana-2', 'LS513-311Cas9_RepB_p6_Avana-2', 'C2BBE1-311Cas9 Rep A p5_Avana-3', 'C2BBE1-311Cas9 Rep B p5_Avana-3', 'C2BBE1-311Cas9 Rep C p5_Avana-3', '253J-311Cas9_RepA_p5_Avana-3', 'HCC827-311Cas9 Rep A p6_Avana-3', 'HCC827-311Cas9 Rep B p6_Avana-3', 'HCC827-311Cas9 Rep C p6_Avana-3', 'ONCO-DG-1-311Cas9_RepA_p6_Avana-3', 'ONCO-DG-1-311Cas9_RepB_p6_Avana-3', 'Hs 294T_A101D-311Cas9_RepA_p6_Avana-3', 'Hs 294T_A101D-311Cas9_RepB_p6_Avana-3', 'NCI-H1581-311Cas9_RepA_p6_Avana-2', 'NCI-H1581-311Cas9_RepB_p6_Avana-2', 'SKBR3-311Cas9_RepA_p6_Avana-3', 'SKBR3-311Cas9_RepB_p6_Avana-3', 'T24-311Cas9_RepA_p6_Avana-3', 'T24-311Cas9_RepB_p6_Avana-3', 'MCF7-311cas9_RepA_p4_Avana-3', 'MCF7-311cas9_RepB_p4_Avana-3', 'NCI-H1693-311Cas9 Rep A p4_Avana-3', 'NCI-H1693-311Cas9 Rep B p4_Avana-3', 'NCI-H1693-311Cas9 Rep C p4_Avana-3', 'NCI-H1693-311Cas9 Rep D p4_Avana-3', 'PA-TU-8988S_PA-TU-8988T-311cas9_RepAB_p6_Avana-3', 'PA-TU-8988S_PA-TU-8988T-311cas9_RepB_p6_Avana-3', 'OPM2-311Cas9_RepA_p6_Avana-3', 'OPM2-311Cas9_RepB_p6_Avana-3', 'CH157MN-311cas9_RepA_p6_Avana-3', 'CH157MN-311cas9_RepB_p6_Avana-3', '253J-BV-311Cas9_RepA_p6_Avana-3', '253J-BV-311Cas9_RepB_p6_Avana-3', 'KPL-1-311Cas9_RepA_p6_Avana-2', 'KPL-1-311Cas9_RepB_p6_Avana-2', 'KPL-1-311Cas9_RepC_p6_Avana-2', 'HCC827GR5-311Cas9_RepA_p5_Avana-3', 'HCC827GR5-311Cas9_RepB_p5_Avana-3', 'PC-14-311Cas9 Rep A p6_Avana-3', 'PC-14-311Cas9 Rep B p6_Avana-3', 'PC-14-311Cas9 Rep C p6_Avana-3', 'NCI-H1650-311cas9_RepA_p6_Avana-3', 'NCI-H1650-311cas9_RepB_p6_Avana-3', 'U343-311Cas9_RepA_p6_Avana-3', 'U343-311Cas9_RepB_p6_Avana-3', 'S-117-311Cs9_RepA_p6_Avana-3', 'S-117-311Cs9_RepB_p6_Avana-3', 'SK-N-MC-311cas9 Rep A p5_Avana-3', 'SK-N-MC-311cas9 Rep B p5_Avana-3', 'SK-N-MC-311cas9 Rep C p5_Avana-3', 'U118MG-311Cas9_RepA_p5_Avana-3', 'U118MG-311Cas9_RepB_p5_Avana-3', 'RD-ES-311Cas9_RepA_p6_Avana-3', 'RD-ES-311Cas9_RepB_p6_Avana-3', 'Panc.02.03-311cas9 Rep A p6_Avana-3', 'Panc.02.03-311cas9 Rep B p6_Avana-3', 'Panc.02.03-311cas9 Rep C p6_Avana-3', 'Panc.02.03-311cas9 Rep D p6_Avana-3', 'MV4;11-311Cas9_RepA_p6_Avana-2', 'MV4;11-311Cas9_RepB_p6_Avana-2', 'GCIY -311Cas9_RepA_p4_Avana-3', 'GCIY -311Cas9_RepB_p4_Avana-3', 'TOV112D-311Cas9_RepA_p6_Avana-3', 'TOV112D-311Cas9_RepB_p6_Avana-3', 'A673 AVANA-4_RepA_p6_Avana-3', 'A673 AVANA-4_RepB_p6_Avana-3', 'Karpas-299-311Cas9 Rep A p5_Avana-3', 'Karpas-299-311Cas9 Rep B p5_Avana-3', 'Karpas-299-311Cas9 Rep C p5_Avana-3', 'HT1080 -311Cas9_RepA_p6_Avana-3', 'HT1080 -311Cas9_RepB_p6_Avana-3', 'D283MED-311cas9_RepA_p6_Avana-2', 'D283MED-311cas9_RepB_p6_Avana-2', 'D283MED-311cas9_RepC_p6_Avana-2', 'PANC1005-311Cas9_RepA_p6_Avana-3', 'PANC1005-311Cas9_RepB_p6_Avana-3', 'HS683-311Cas9_RepA_p6_Avana-3', 'HS683-311Cas9_RepB_p6_Avana-3', '697-311CAS9_RepA_p6_Avana-3', '697-311CAS9_RepB_p6_Avana-3', 'MEG01-311cas9_RepA_p6_Avana-3', 'MEG01-311cas9_RepB_p6_Avana-3', 'KU812-311cas9-RepA-p6_Avana-3', 'KU812-311cas9-RepB-p6_Avana-3', 'U87-MG-311Cas9_RepA_p6_Avana-3', 'U87-MG-311Cas9_RepB_p6_Avana-3', 'NCO2-311cas9_RepA_p5_Avana-3', 'NCO2-311cas9_RepB_p5_Avana-3', 'MJ-311cas9-RepA-p6_Avana-4', 'MJ-311cas9-RepB-p6_Avana-4', 'MHH-NB-11-311Cas9 Rep A p4_Avana-3', 'MHH-NB-11-311Cas9 Rep B p4_Avana-3', 'MHH-NB-11-311Cas9 Rep C p4_Avana-3', 'BDCM-311Cas9_RepA_p6_Avana-3', 'BDCM-311Cas9_RepB_p6_Avana-3', 'G-292, Clone A141B1-311Cas9_RepA_p5_Avana-3', 'G-292, Clone A141B1-311Cas9_RepB_p5_Avana-3', 'T3M-4-311Cas9_RepA_p6_Avana-3', 'ACCMES01-311cas9_RepA_p6_Avana-3', 'ACCMES01-311cas9_RepB_p6_Avana-3', 'SK-ES-1-311Cas9_RepA_p5_Avana-3', 'SK-ES-1-311Cas9_RepB_p5_Avana-3', 'PC3-311cas9_RepA_p6_Avana-3', 'PC3-311cas9_RepB_p6_Avana-3', 'NCI-H2452-311Cas9_RepA_p5_Avana-3', 'NCI-H2452-311Cas9_RepB_p5_Avana-3', 'PANC0504-311cas9-RepA-p6_Avana-4', 'PANC0504-311cas9-RepB-p6_Avana-4', 'D341MED-311cas9 Rep A p5_Avana-3', 'D341MED-311cas9 Rep B p5_Avana-3', 'D341MED-311cas9 Rep C p5_Avana-3', 'G-401-311Cas9_RepA_p6_Avana-2', 'G-401-311Cas9_RepB_p6_Avana-2', 'ZR-75-1-311Cas9_RepA_p5_Avana-2', 'ZR-75-1-311Cas9_RepB_p5_Avana-2', 'GAMG-311Cas9_RepA_p6_Avana-3', 'GAMG-311Cas9_RepB_p6_Avana-3', 'Sima-311cas9 Rep A p6_Avana-3', 'Sima-311cas9 Rep B p6_Avana-3', 'Sima-311cas9 Rep C p6_Avana-3', 'RH41-311cas9-RepA-p6_Avana-4', 'RH41-311cas9-RepB-p6_Avana-4', 'KE37-311Cas9-RepA-p6_Avana-4', 'KE37-311Cas9-RepB-p6_Avana-4', 'JVM-2-311Cas9_RepA_p6_Avana-3', 'JVM-2-311Cas9_RepB_p6_Avana-3', 'KP-3-311Cas9 Rep A p5_Avana-3', 'KP-3-311Cas9 Rep B p5_Avana-3', 'KP-3-311Cas9 Rep C p5_Avana-3', 'HCC1187-311Cas9_RepA_p6_Avana-3', 'HCC1187-311Cas9_RepB_p6_Avana-3', 'SIGM5-311CAS9_RepA_p5_Avana-3', 'SIGM5-311CAS9_RepB_p5_Avana-3', 'OCI-AML2-311cas9_RepA_p6_Avana-3', 'OCI-AML2-311cas9_RepB_p6_Avana-3', 'SU8686-311Cas9-RepA-p6_Avana-3', 'Vcap-304Cas9_RepA_p4_Avana-3', 'Vcap-304Cas9_RepB_p4_Avana-3', 'OAW28-311Cas9_RepA_p4_Avana-3', 'OAW28-311Cas9_RepB_p4_Avana-3', 'HUP-T3-311cas9 Rep A p6_Avana-3', 'HUP-T3-311cas9 Rep B p6_Avana-3', 'HUP-T3-311cas9 Rep C p6_Avana-3', 'HUP-T3-311cas9 Rep D p6_Avana-3', 'CHP-212-311CAS9 Rep A p5_Avana-3', 'CHP-212-311CAS9 Rep B p5_Avana-3', 'CHP-212-311CAS9 Rep C p5_Avana-3', 'CHP-212-311CAS9 Rep D p5_Avana-3', 'COV434-311cas9 Rep A p6_Avana-3', 'COV434-311cas9 Rep B p6_Avana-3', 'COV434-311cas9 Rep C p6_Avana-3', 'OCILY19-311cas9-RepA-p6_Avana-4', 'OCILY19-311cas9-RepB-p6_Avana-4', 'SLR20-311Cas9_RepA_p6_Avana-3', 'LN319-311CAS9_RepA_p6_Avana-3', 'LN319-311CAS9_RepB_p6_Avana-3', 'JHOS-2-311Cas9_RepA_p6_Avana-3', 'Hs729-311Cas9_RepA_p6_Avana-3', 'Hs729-311Cas9_RepB_p6_Avana-3', '8-MG-BA-311Cas9_RepA_p5_Avana-3', '8-MG-BA-311Cas9_RepB_p5_Avana-3', 'CFPAC-1-311Cas9 Rep A p6_Avana-3', 'CFPAC-1-311Cas9 Rep B p6_Avana-3', 'CFPAC-1-311Cas9 Rep D p6_Avana-3', 'SNU308-311Cas9_RepA_p5_Avana-3', 'SNU308-311Cas9_RepB_p5_Avana-3', 'SNU308-311Cas9_RepC_p5_Avana-3', 'CAL-29-311Cas9_RepA_p6_Avana-2', 'CAL-29-311Cas9_RepB_p6_Avana-2', 'HCC2429-311Cas9_RepA_p6_Avana-3', 'HCC2429-311Cas9_RepB_p6_Avana-3', 'RERF-GC-1B-311Cas9_RepA_p6_Avana-3', 'RERF-GC-1B-311Cas9_RepB_p6_Avana-3', 'SKLMS1-311cas9-RepA-p6_Avana-4', 'SKLMS1-311cas9-RepB-p6_Avana-4', 'THP-1 AVANA-4 Rep A p5_Avana-3', 'THP-1 AVANA-4 Rep B p5_Avana-3', 'THP-1 AVANA-4 Rep C p5_Avana-3', 'T47D-311Cas9-RepA-p6_Avana-4', 'T47D-311Cas9-RepB-p6_Avana-4', 'HS578T-311cas9_RepA_p5_Avana-2', 'HS578T-311cas9_RepB_p5_Avana-2', 'HS578T-311cas9_RepC_p5_Avana-2', 'JM1-311cas9_RepA_p6_Avana-3', 'JM1-311cas9_RepB_p6_Avana-3', 'M059K-311Cas9_RepA_p5_Avana-3', 'M059K-311Cas9_RepB_p5_Avana-3', 'NCI-H2052-311Cas9_RepA_p6_Avana-3', 'OSRC2-311Cas9_RepA_p5_Avana-3', 'OSRC2-311Cas9_RepB_p5_Avana-3', 'BT12-311Cas9-RepA-P6_Avana-4', 'BT12-311Cas9-RepB-P6_Avana-4', 'CORL105-311Cas9-RepA-p6_Avana-4', 'SW579-311Cas9_RepA_p6_Avana-3', 'SW579-311Cas9_RepB_p6_Avana-3', 'Panc1-311Cas9_RepA_p6_Avana-3', 'Panc1-311Cas9_RepB_p6_Avana-3', 'KE97-311Cas9_RepA_p6_Avana-3', 'KE97-311Cas9_RepB_p6_Avana-3', 'NOMO-1-311Cas9_RepA_p4_Avana-2', 'NOMO-1-311Cas9_RepB_p4_Avana-2', 'RD-311Cas9_RepA_p5_Avana-3', 'RD-311Cas9_RepB_p5_Avana-3', 'RH18DM-311cas9_RepA_p6_Avana-3', 'RH18DM-311cas9_RepB_p6_Avana-3', 'TM87-311Cas9_RepA_p6_Avana-4', 'TM87-311Cas9_RepB_p6_Avana-4', 'CAL62-311cas9-RepA-p6_Avana-3', 'CAL62-311cas9-RepB-p6_Avana-3', 'Hs766T-311Cas9_RepA_p6_Avana-2', 'Hs766T-311Cas9_RepB_p6_Avana-2', 'SNU869-311Cas9_RepA_p4_Avana-3', 'L363-311Cas9_RepA_p6_Avana-3', 'L363-311Cas9_RepB_p6_Avana-3', 'COR-L311-311Cas9_RepA_p6_Avana-3', 'SCC25-311Cas9_RepA_p6_Avana-3', 'SCC25-311Cas9_RepB_p6_Avana-3', 'RCC10RGB-311Cas9_RepA_p6_Avana-3', 'RCC10RGB-311Cas9_RepB_p6_Avana-3', 'HDMYZ-311Cas9-RepA-P6_Avana-4', 'HDMYZ-311Cas9-RepB-P6_Avana-4', 'BHT101-311cas9-RepA-p6_Avana-4', 'BHT101-311cas9-RepB-p6_Avana-4', 'set2-311cas9-RepA-p6_Avana-4', 'set2-311cas9-RepB-p6_Avana-4', 'EOL1-311Cas9_RepA_p6_Avana-3', 'EOL1-311Cas9_RepB_p6_Avana-3', 'NMC-G1-311Cas9_RepA_p5_Avana-3', 'NMC-G1-311Cas9_RepB_p5_Avana-3', 'COLO320-311Cas9 Rep A p6_Avana-3', 'COLO320-311Cas9 Rep B p6_Avana-3', 'COLO320-311Cas9 Rep C p6_Avana-3', 'NH6-311Cas9_RepA_p4_Avana-3', 'NH6-311Cas9_RepB_p4_Avana-3', 'LP-1-311Cas9_RepA_p6_Avana-2', 'LP-1-311Cas9_RepB_p6_Avana-2', 'C8166-311cas9_RepA_p6_Avana-3', 'C8166-311cas9_RepB_p6_Avana-3', 'DETROIT562-311Cas9_RepA_p3_Avana-3', 'DETROIT562-311Cas9_RepB_p3_Avana-3', 'U178-311Cas9_RepA_p5_Avana-3', 'U178-311Cas9_RepB_p5_Avana-3', 'SNU-1079-311Cas9_RepA_p6_Avana-3', 'SNU-1079-311Cas9_RepB_p6_Avana-3', 'CADO-ES-1-311cas9_RepA_p6_Avana-3', 'CADO-ES-1-311cas9_RepB_p6_Avana-3', 'Daoy-311Cas9_RepA_p6_Avana-3', 'Daoy-311Cas9_RepB_p6_Avana-3', 'CAL120-311Cas9-RepA-p6_Avana-3', 'CAL120-311Cas9-RepB-p6_Avana-3', 'LN382-311CAS9_RepA_p6_Avana-3', 'LN382-311CAS9_RepB_p6_Avana-3', 'JHESOAD1-311cas9-RepA-p6_Avana-4', 'JHESOAD1-311cas9-RepB-p6_Avana-4', 'JHH-6-311Cas9_RepA_p6_Avana-3', 'JHH-6-311Cas9_RepB_p6_Avana-3', 'A375-311cas9-RepA-p6_Avana-3', 'A375-311cas9-RepB-p6_Avana-3', 'SNU-398-31Cas9_RepA_p5_Avana-3', 'SNU-398-31Cas9_RepB_p5_Avana-3', 'ASPC-1-311Cas9 Rep A p6_Avana-3', 'ASPC-1-311Cas9 Rep B p6_Avana-3', 'ASPC-1-311Cas9 Rep C p6_Avana-3', 'ASPC-1-311Cas9 Rep D p6_Avana-3', 'HCC1937-311Cas9_RepA_p5_Avana-3', 'HCC1937-311Cas9_RepB_p5_Avana-3', 'SUP-M2-311Cas9 Rep A p4_Avana-3', 'SUP-M2-311Cas9 Rep B p4_Avana-3', 'SUP-M2-311Cas9 Rep C p4_Avana-3', 'SUP-M2-311Cas9 Rep D p4_Avana-3', 'KP-N-YN-311Cas9 Rep A p3_Avana-2', 'KP-N-YN-311Cas9 Rep B p3_Avana-2', 'KP-N-YN-311Cas9 Rep C p3_Avana-2', 'BICR31-311Cas9_RepA_p6_Avana-3', 'BICR31-311Cas9_RepB_p6_Avana-3', 'KALS1 -311Cas9_RepA_p6_Avana-3', 'KALS1 -311Cas9_RepB_p6_Avana-3', 'U251MG-311Cas9_RepA_p6_Avana-2', 'U251MG-311Cas9_RepB_p6_Avana-2', 'DEL-311cas9_RepA_p6_Avana-3', 'DEL-311cas9_RepB_p6_Avana-3', 'CAKI-2-311Cas9_RepA_p6_Avana-3', 'CAKI-2-311Cas9_RepB_p6_Avana-3', 'Panc.04.03-311Cas9 Rep A p5_Avana-3', 'Panc.04.03-311Cas9 Rep B p5_Avana-3', 'Panc.04.03-311Cas9 Rep C p5_Avana-3', 'Panc.04.03-311Cas9 Rep D p5_Avana-3', 'JHOM-1-311cas9 Rep A p6_Avana-2', 'JHOM-1-311cas9 Rep B p6_Avana-2', 'JHOM-1-311cas9 Rep C p6_Avana-2', 'SCC4-311cas9_RepA_p6_Avana-3', 'SCC4-311cas9_RepB_p6_Avana-3', 'HUG1N-311cas9_RepA_p6_Avana-3', 'HUG1N-311cas9_RepB_p6_Avana-3', 'RT4-311Cas9_RepA_p6_Avana-3', 'RT4-311Cas9_RepB_p6_Avana-3', 'DAN-G-311Cas9 Rep A p6_Avana-3', 'DAN-G-311Cas9 Rep B p6_Avana-3', 'DAN-G-311Cas9 Rep C p6_Avana-3', 'DAN-G-311Cas9 Rep D p6_Avana-3', 'DKMG-311Cas9_RepA_p5_Avana-3', 'DKMG-311Cas9_RepB_p5_Avana-3', 'SLR23-311Cas9_RepA_p6_Avana-3', 'SLR23-311Cas9_RepB_p6_Avana-3', 'OCUM-1-311Cas9_RepA_p4_Avana-3', 'OCUM-1-311Cas9_RepB_p4_Avana-3', 'AU565-311Cas9_RepA_p6_Avana-2', 'AU565-311Cas9_RepB_p6_Avana-2', 'AU565-311Cas9_RepC_p6_Avana-2', 'CL-11-311Cas9_RepA_p6_Avana-3', 'CL-11-311Cas9_RepB_p6_Avana-3', 'KMRC20-311Cas9_RepA_p6_Avana-3', 'KMRC20-311Cas9_RepB_p6_Avana-3', 'NCI-H2887-311cas9_RepA_p5_Avana-2', 'NCI-H2887-311cas9_RepB_p5_Avana-2', 'NCI-H2887-311cas9_RepC_p5_Avana-2', 'LS1034-311cas9 Rep A p5_Avana-2', 'LS1034-311cas9 Rep B p5_Avana-2', 'LS1034-311cas9 Rep C p5_Avana-2', 'COLO201-311Cas9_RepA_p6_Avana-3', 'COLO201-311Cas9_RepB_p6_Avana-3', 'LMSU-311Cas9_RepA_p6_Avana-3', 'LMSU-311Cas9_RepB_p6_Avana-3', 'Cov318-311cas9_RepA_p4_Avana-2', 'Cov318-311cas9_RepC_p4_Avana-2', 'CORL279-311cas9_RepA_p4_Avana-3', 'CORL279-311cas9_RepB_p4_Avana-3', 'DU4475 -311Cas9_RepA_p6_Avana-3', 'DU4475 -311Cas9_RepB_p6_Avana-3', 'KELLY-311Cas9 Rep A p6_Avana-3', 'KELLY-311Cas9 Rep B p6_Avana-3', 'KELLY-311Cas9 Rep D p6_Avana-3', 'SK-N-AS-311Cas9 Rep A p6_Avana-3', 'SK-N-AS-311Cas9 Rep B p6_Avana-3', 'SK-N-AS-311Cas9 Rep C p6_Avana-3', 'RERF-LC-AI-311cas9_RepA_p6_Avana-3', 'RERF-LC-AI-311cas9_RepB_p6_Avana-3', 'UOK101-311Cas9_RepA_p6_Avana-3', 'UOK101-311Cas9_RepB_p6_Avana-3', 'KASUMI-1-311cas9_RepA_p6_Avana-3', 'KASUMI-1-311cas9_RepB_p6_Avana-3', 'Calu-6-311Cas9_RepA_p6_Avana-3', 'Calu-6-311Cas9_RepB_p6_Avana-3', 'KP4-311Cas9 Rep A p7_Avana-3', 'KP4-311Cas9 Rep B p7_Avana-3', 'KP4-311Cas9 Rep C p7_Avana-3', 'KP4-311Cas9 Rep D p7_Avana-3', 'SNU-213-311Cas9 Rep A p5_Avana-3', 'SNU-213-311Cas9 Rep B p5_Avana-3', 'SNU-213-311Cas9 Rep C p5_Avana-3', 'SNU-213-311Cas9 Rep D p5_Avana-3', 'HDLM2-311Cas9_RepA_p4_Avana-3', 'SNU-245-311Cas9_RepA_p6_Avana-3', 'SNU-245-311Cas9_RepB_p6_Avana-3', 'SUDHL10-311Cas9-RepA-P6_Avana-4', 'SUDHL10-311Cas9-RepB-P6_Avana-4', 'SLR24-311Cas9_RepA_p4_Avana-3', 'SLR24-311Cas9_RepB_p4_Avana-3', 'SF539-311cas9_RepA_p6_Avana-3', 'SF539-311cas9_RepB_p6_Avana-3', 'Hs852.T-311Cas9_RepA_p5_Avana-3', 'Hs852.T-311Cas9_RepB_p5_Avana-3', 'HCC38-311Cas9_RepA_p6_Avana-3', 'HCC38-311Cas9_RepB_p6_Avana-3', 'HCC1419-311Cas9_RepA_p6_Avana-3', 'HCC1419-311Cas9_RepB_p6_Avana-3', 'COV362-311Cas9 Rep A p4_Avana-2', 'COV362-311Cas9 Rep B p4_Avana-2', 'COV362-311Cas9 Rep C p4_Avana-2', 'EW502-311Cas9_RepA_p6_Avana-3', 'EW502-311Cas9_RepB_p6_Avana-3', 'SNU-840 311Cas9_RepA_p6_Avana-2', 'SNU-840 311Cas9_RepB_p6_Avana-2', 'SNU-840 311Cas9_RepC_p6_Avana-2', 'KP-2-311Cas9 Rep A p5_Avana-3', 'KP-2-311Cas9 Rep B p5_Avana-3', 'KP-2-311Cas9 Rep C p5_Avana-3', 'SNU-1033-311Cas9_RepA_p3_Avana-3', 'SNU-1033-311Cas9_RepB_p3_Avana-3', 'NUDUL1-311cas9-RepA-p6_Avana-4', 'NUDUL1-311cas9-RepB-p6_Avana-4', 'BT549-311cas9 Rep A p5_Avana-2', 'BT549-311cas9 Rep B p5_Avana-2', 'BT549-311cas9 Rep C p5_Avana-2', 'NCI-H209-311Cas9_RepA_p6_Avana-3', 'NCI-H209-311Cas9_RepB_p6_Avana-3', 'OV90-311Cas9_RepA_p6_Avana-3', 'OV90-311Cas9_RepB_p6_Avana-3', 'NCI-H841-311as9_RepA_p6_Avana-3', 'NCI-H841-311as9_RepB_p6_Avana-3', 'KLE-311Cas9_RepA_p6_Avana-3', 'KLE-311Cas9_RepB_p6_Avana-3', 'NB-4-311cas9 Rep A p6_Avana-3', 'NB-4-311cas9 Rep B p6_Avana-3', 'NB-4-311cas9 Rep C p6_Avana-3', 'EM-2-311Cas9_RepA_p6_Avana-3', 'EM-2-311Cas9_RepB_p6_Avana-3', 'OUMS-23-311Cas9 Rep A p5_Avana-3', 'OUMS-23-311Cas9 Rep B p5_Avana-3', 'OUMS-23-311Cas9 Rep C p5_Avana-3', 'SNU1077-311Cas9_RepA_p6_Avana-3', 'SNU1077-311Cas9_RepB_p6_Avana-3', 'SNU-5-311Cas9_RepA_p6_Avana-4', 'Wm-115-311Cas9_RepA_p6_Avana-3', 'Wm-115-311Cas9_RepB_p6_Avana-3', 'ECGI10-311cas9_RepA_p6_Avana-3', 'ECGI10-311cas9_RepB_p6_Avana-4', 'PK-1_KLM-1-311Cas9_RepA_p6_Avana-3', 'PK-1_KLM-1-311Cas9_RepB_p6_Avana-3', 'EFO-21 311Cas9_RepA_p5_Avana-2', 'EFO-21 311Cas9_RepB_p5_Avana-2', 'EFO-21 311Cas9_RepC_p5_Avana-2', 'IMR32-311cas9 Rep A p3_Avana-3', 'IMR32-311cas9 Rep B p3_Avana-3', 'IMR32-311cas9 Rep D p3_Avana-3', 'NCI-H2122-311cas9 Rep A p5_Avana-3', 'NCI-H2122-311cas9 Rep B p5_Avana-3', 'NCI-H2122-311cas9 Rep C p5_Avana-3', 'NCI-H2122-311cas9 Rep D p5_Avana-3', 'SK-N-BE_2_-311Cas9 Rep A p6_Avana-3', 'SK-N-BE_2_-311Cas9 Rep B p6_Avana-3', 'SK-N-BE_2_-311Cas9 Rep C p6_Avana-3', 'SK-N-BE_2_-311Cas9 Rep D p6_Avana-3', 'KMRC3-311Cas9-RepA-p6_Avana-4', 'KMRC3-311Cas9-RepB-p6_Avana-4', 'KARPAS-422-311cas9_RepA_p6_Avana-3', 'KARPAS-422-311cas9_RepB_p6_Avana-3', 'SNU-886-311Cas9_RepA_p6_Avana-3', 'SNU-886-311Cas9_RepB_p6_Avana-3', 'TUHR14TKB-311Cas9_RepA_p6_Avana-3', 'TUHR14TKB-311Cas9_RepB_p6_Avana-3', 'TE10-311Cas9_RepA_p6_Avana-3', 'TE10-311Cas9_RepB_p6_Avana-3', 'MPP 89-311Cas9_RepA_p5_Avana-3', 'MPP 89-311Cas9_RepB_p5_Avana-3', 'PSN-1-311Cas9 Rep A p6_Avana-3', 'PSN-1-311Cas9 Rep B p6_Avana-3', 'PSN-1-311Cas9 Rep C p6_Avana-3', 'PSN-1-311Cas9 Rep D p6_Avana-3', 'HT144-311Cas9_RepA_p6_Avana-3', 'HT144-311Cas9_RepB_p6_Avana-3', '42-MG-BA-311Cas9_RepA_p6_Avana-3', '42-MG-BA-311Cas9_RepB_p6_Avana-3', 'JHOC5-311cas9 Rep A p6_20150925_Avana-3', 'JHOC5-311cas9 Rep B p6_20150925_Avana-3', 'JHOC5-311cas9 Rep C p6_20150925_Avana-3', 'SNU620-311cas9-RepA-p6_Avana-4', 'SNU620-311cas9-RepB-p6_Avana-4', 'JURLMK1-311Cas9_RepA_p6_Avana-3', 'JURLMK1-311Cas9_RepB_p6_Avana-3', 'NCIH1395-311Cas9_RepA_p5_Avana-3', 'NCIH1395-311Cas9_RepB_p5_Avana-3', 'CCF-STTG1-311Cas9_RepA_p5_Avana-3', 'CCF-STTG1-311Cas9_RepB_p5_Avana-3', 'EFM19-311cas9_RepA_p5_Avana-2', 'EFM19-311cas9_RepB_p5_Avana-2', 'IST-MES2-311Cas9_RepA_p6_Avana-3', 'IST-MES2-311Cas9_RepB_p6_Avana-3', 'YAPC-311Cas9 Rep A p6_Avana-3', 'YAPC-311Cas9 Rep B p6_Avana-3', 'YAPC-311Cas9 Rep C p6_Avana-3', 'YAPC-311Cas9 Rep D p6_Avana-3', 'DB-311Cas9_RepA_p3_Avana-3', 'DB-311Cas9_RepB_p3_Avana-3', 'MSTO-211H-311Cas9_RepA_p6_Avana-3', 'MSTO-211H-311Cas9_RepB_p6_Avana-3', 'OCIAML3-311CAS9_RepA_p6_Avana-3', 'OCIAML3-311CAS9_RepB_p6_Avana-3', 'NCIH3122-311Cas9_RepA_p6_Avana-3', 'NCIH3122-311Cas9_RepB_p6_Avana-3', 'SR-786-311Cas9_RepB_p6_Avana-3', 'HCC461-Avana4 Rep A p6_Avana-3', 'HCC461-Avana4 Rep B p6_Avana-3', 'HCC461-Avana4 Rep C p6_Avana-3', 'SK-N-FI-311Cas9 Rep A p3_Avana-2', 'SK-N-FI-311Cas9 Rep B p3_Avana-2', 'NCIH522-311Cas9_RepA_p6_Avana-4', 'NCIH522-311Cas9_RepB_p6_Avana-4', 'SNU668-311cas9_RepA_p6_Avana-3', 'KPNRTBM1-311Cas9_RepA_p6_Avana-3', 'JVM3-311cas9_RepA_p6_Avana-4', 'QGP-1-311Cas9 Rep A p6_Avana-3', 'QGP-1-311Cas9 Rep B p6_Avana-3', 'QGP-1-311Cas9 Rep C p6_Avana-3', 'RPMI7951-311Cas9_RepA_p5_Avana-3', 'RPMI7951-311Cas9_RepB_p5_Avana-3', 'COLO-678-311Cas9 Rep A p5_Avana-3', 'COLO-678-311Cas9 Rep C p5_Avana-3', 'COLO-678-311Cas9 Rep D p5_Avana-3', 'HCC1428-311Cas9_RepA_p6_Avana-3', 'HCC1428-311Cas9_RepB_p6_Avana-3', 'TE-15-311cas9_RepA_p6_Avana-3', 'TE-15-311cas9_RepB_p6_Avana-3', 'NCI-H82-311Cas9_RepA_p6_Avana-3', 'NCI-H82-311Cas9_RepB_p6_Avana-3', 'MKN45 -311Cas9_RepA_p6_Avana-3', 'MKN45 -311Cas9_RepB_p6_Avana-3', 'JeKo1-311Cas9_RepA_p6_Avana-3', 'JeKo1-311Cas9_RepB_p6_Avana-3', 'MG63-311cas9-RepA-p6_Avana-4', 'NCI-H508-311Cas9_RepA_p5_Avana-2', 'NCI-H508-311Cas9_RepB_p5_Avana-2', 'NCI-H508-311Cas9_RepC_p5_Avana-2', 'SKHEP1-311Cas9_RepA_p6_Avana-3', 'SKHEP1-311Cas9_RepB_p6_Avana-3', 'MOLM-13-311cas9 Rep A p5_Avana-3', 'MOLM-13-311cas9 Rep B p5_Avana-3', 'MOLM-13-311cas9 Rep C p5_Avana-3', 'SK-MM-2-311Cas9_RepA_p6_Avana-3', 'SK-MM-2-311Cas9_RepB_p6_Avana-3', 'U2-OS-311Cas9_RepA_p6_Avana-3', 'U2-OS-311Cas9_RepB_p6_Avana-3', 'SUDHL4-311Cas9_RepA_p6_Avana-3', 'SUDHL4-311Cas9_RepB_p6_Avana-3', 'SK-N-DZ-311Cas9_RepA_p5_Avana-2', 'SK-N-DZ-311Cas9_RepB_p5_Avana-2', 'SNU-1105-311Cas9_RepA_p6_Avana-3', 'SNU-1105-311Cas9_RepB_p6_Avana-3', 'SNU626-311Cas9-RepA-p5_Avana-3', 'SNU626-311Cas9-RepB-p5_Avana-3', 'RL-311cas9-RepA-p6_Avana-3', 'RL-311cas9-RepB-p6_Avana-3', 'SKM1-311cas9 Rep A p6_20150925_Avana-3', 'SKM1-311cas9 Rep B p6_20150925_Avana-3', 'SKM1-311cas9 Rep C p6_20150925_Avana-3', 'HCC1143-311cas9 Rep A p6_Avana-2', 'HCC1143-311cas9 Rep B p6_Avana-2', 'G402-311Cas9_RepA_p6_Avana-3', 'G402-311Cas9_RepB_p6_Avana-3', 'SF-295-311Cas9_RepA_p6_Avana-3', 'SF-295-311Cas9_RepB_p6_Avana-3', 'SNU-478-311Cas9_RepA_p6_Avana-3', 'SNU-478-311Cas9_RepB_p6_Avana-3', 'NCI-H647-311cas9_RepA_p6_Avana-3', 'NCI-H647-311cas9_RepB_p6_Avana-3', 'KMS12BM-311Cas9_RepA_p5_Avana-3', 'KMS12BM-311Cas9_RepB_p5_Avana-3', 'T84-311Cas9 Rep A p6_Avana-3', 'T84-311Cas9 Rep C p6_Avana-3', 'T84-311Cas9 Rep D p6_Avana-3', 'OE33-311Cas9_RepA_p4_Avana-2', 'OE33-311Cas9_RepB_p4_Avana-2', 'SKRC20-311Cas9_RepA_p6_Avana-3', 'SKRC20-311Cas9_RepB_p6_Avana-3', 'TF-1-311cas9 Rep A p5_20150925_Avana-3', 'TF-1-311cas9 Rep B p5_20150925_Avana-3', 'TF-1-311cas9 Rep C p5_20150925_Avana-3', 'H4-311cas9_RepA_p6_Avana-3', 'H4-311cas9_RepB_p6_Avana-3', 'LUDLU1-311Cas9_RepA_p4_Avana-2', 'LUDLU1-311Cas9_RepB_p4_Avana-2', 'MHHES1-311Cas9_RepA_p6_Avana-4', 'MHHES1-311Cas9_RepB_p6_Avana-4', 'HLF-311Cas9_RepA_p6_Avana-3', 'HLF-311Cas9_RepB_p6_Avana-3', 'NCI-H520-311Cas9 Rep A p6_Avana-3', 'NCI-H520-311Cas9 Rep B p6_Avana-3', 'NCI-H520-311Cas9 Rep C p6_Avana-3', 'J82-311Cas9_RepA_p5_Avana-3', 'J82-311Cas9_RepB_p5_Avana-3', 'TEN-311Cas9_RepA_p6_Avana-3', 'TEN-311Cas9_RepB_p6_Avana-3', 'Ri1-311cas9_RepA_p6_Avana-4', 'COLO-800-311Cas9_RepA_p6_Avana-3', 'COLO-800-311Cas9_RepB_p6_Avana-3', 'BL70-311cas9_RepA_p6_Avana-3', 'BL70-311cas9_RepB_p6_Avana-3', 'NCI-H747-311cas9 Rep A p3_Avana-2', 'NCI-H747-311cas9 Rep B p3_Avana-2', '

In [8]:
guide.head(3)

,sgRNA,GenomeAlignment,nAlignments,Gene,DropReason,UsedByChronos
0,AAAAAAATCCAGCAATGCAG,chr10_110964620_+,1.0,SHOC2 (8036),NaN,True
1,AAAAAACCCGTAGATAGCCT,chr12_95003615_+,1.0,NDUFA12 (55967),NaN,True
2,AAAAAAGAAGAAAAAACCAG,chr4_75970356_-,1.0,SDAD1 (55153),NaN,True

In [9]:
guide['Gene'].nunique()

18531

In [10]:
seqmap.head()

,SequenceID,ScreenID,Days,pDNABatch,Replicate,ModelID,ExcludeFromCRISPRCombined,ScreenType,Library,ModelConditionID,DrugTreated,PassesQC
0,Colo699-311cas9-RepA-p6_Avana-4,SC-001041.AV01,21,Avana-4,A,ACH-001041,False,2DS,Avana,MC-001041-CkXW,False,True
1,Colo699-311cas9-RepB-p6_Avana-4,SC-001041.AV01,21,Avana-4,B,ACH-001041,False,2DS,Avana,MC-001041-CkXW,False,True
2,HSB-2-311cas9_RepA_p4_Avana-3,SC-001737.AV01,21,Avana-3,A,ACH-001737,False,2DS,Avana,MC-001737-6D5K,False,True
3,HSB-2-311cas9_RepB_p4_Avana-3,SC-001737.AV01,21,Avana-3,B,ACH-001737,False,2DS,Avana,MC-001737-6D5K,False,True
4,NCIH1339-311Cas9_RepA_p6_Avana-3,SC-000921.AV01,21,Avana-3,A,ACH-000921,False,2DS,Avana,MC-000921-P628,False,True

In [11]:
#seqmap['pDNABatch'].unique()
print(raw.iloc[:, -3:].head(3))
print("---------------------------------------------------------------------------------------------------------------------------------------")
#print(seqmap[seqmap['pDNABatch'].str.startswith('Avana', na=False)].head(3))
seqmap[seqmap['pDNABatch'].str.startswith('Avana', na=False)].head()

   pDNA_batch_Avana-4  pDNA_batch_Avana-3  pDNA_batch_Avana-2
0              2165.0              6327.0               190.5
1              3127.5              9322.0               289.0
2               517.0              2030.5                41.5
---------------------------------------------------------------------------------------------------------------------------------------

,SequenceID,ScreenID,Days,pDNABatch,Replicate,ModelID,ExcludeFromCRISPRCombined,ScreenType,Library,ModelConditionID,DrugTreated,PassesQC
0,Colo699-311cas9-RepA-p6_Avana-4,SC-001041.AV01,21,Avana-4,A,ACH-001041,False,2DS,Avana,MC-001041-CkXW,False,True
1,Colo699-311cas9-RepB-p6_Avana-4,SC-001041.AV01,21,Avana-4,B,ACH-001041,False,2DS,Avana,MC-001041-CkXW,False,True
2,HSB-2-311cas9_RepA_p4_Avana-3,SC-001737.AV01,21,Avana-3,A,ACH-001737,False,2DS,Avana,MC-001737-6D5K,False,True
3,HSB-2-311cas9_RepB_p4_Avana-3,SC-001737.AV01,21,Avana-3,B,ACH-001737,False,2DS,Avana,MC-001737-6D5K,False,True
4,NCIH1339-311Cas9_RepA_p6_Avana-3,SC-000921.AV01,21,Avana-3,A,ACH-000921,False,2DS,Avana,MC-000921-P628,False,True

In [12]:
seqmap['Library'].unique()

array(['Avana', 'Humagne-CD', 'KY'], dtype=object)

In [13]:
print('Days: ',seqmap['Days'].unique())
print('pDNA Batch: ',seqmap['pDNABatch'].unique())
print('SCreen Type: ',seqmap['ScreenType'].unique())
print('Library: ',seqmap['Library'].unique())
print('DrugTreated: ',seqmap['DrugTreated'].unique())
print(seqmap['ExcludeFromCRISPRCombined'].unique())

Days:  [21  0 14 15 22]
pDNA Batch:  ['Avana-4' 'Avana-3' 'Avana-2' 'CD-HiSeq' 'CD-NovaSeq' 'KY-1' 'KY-2']
SCreen Type:  ['2DS' 'pDNA']
Library:  ['Avana' 'Humagne-CD' 'KY']
DrugTreated:  [False nan]
[False]

In [14]:
# seqmap[seqmap['SequenceID'].str.startswith('Colo699-311cas9')]
seqmap[seqmap['ScreenType']=='pDNA']

,SequenceID,ScreenID,Days,pDNABatch,Replicate,ModelID,ExcludeFromCRISPRCombined,ScreenType,Library,ModelConditionID,DrugTreated,PassesQC
2281,pDNA_batch_Avana-4,pDNA,0,Avana-4,NaN,pDNA,False,pDNA,Avana,pDNA,NaN,True
2282,pDNA_batch_Avana-3,pDNA,0,Avana-3,NaN,pDNA,False,pDNA,Avana,pDNA,NaN,True
2283,pDNA_batch_Avana-2,pDNA,0,Avana-2,NaN,pDNA,False,pDNA,Avana,pDNA,NaN,True
2348,pDNA_CD-NovaSeq_0,pDNA,0,CD-NovaSeq,NaN,pDNA,False,pDNA,Humagne-CD,pDNA,NaN,True
2349,pDNA_CD-HiSeq_0,pDNA,0,CD-HiSeq,NaN,pDNA,False,pDNA,Humagne-CD,pDNA,NaN,True
3236,pDNA_batch_KY-1,pDNA,0,KY-1,NaN,pDNA,False,pDNA,KY,pDNA,NaN,True
3237,pDNA_batch_KY-2,pDNA,0,KY-2,NaN,pDNA,False,pDNA,KY,pDNA,NaN,True

In [15]:
print(seqmap[seqmap["PassesQC"] == True].shape)
print (seqmap.shape)
print(seqmap["pDNABatch"].unique())

(3094, 12)
(3238, 12)
['Avana-4' 'Avana-3' 'Avana-2' 'CD-HiSeq' 'CD-NovaSeq' 'KY-1' 'KY-2']

## **<span style="color:orangered;">Step 3 — Cleaning the data and</span>**

In [16]:
seqmap[seqmap['SequenceID'].isna()]

Empty DataFrame
Columns: [SequenceID, ScreenID, Days, pDNABatch, Replicate, ModelID, ExcludeFromCRISPRCombined, ScreenType, Library, ModelConditionID, DrugTreated, PassesQC]
Index: []

In [17]:
screen_pass = seqmap[seqmap['SequenceID'].notna() & 
                  (seqmap['ScreenType'] == '2DS') &
                  (seqmap['ExcludeFromCRISPRCombined'] == False) &
                  (seqmap['Library']=='Avana') & 
                  seqmap['PassesQC'] == True]

pdna_pass = seqmap[seqmap['SequenceID'].notna() & 
    (seqmap['ScreenType']== 'pDNA') &
    seqmap['pDNABatch'].notna()]

print('seqmap shape:', seqmap.shape)
print('screen_pass shape:', screen_pass.shape)
print(f"pdna_pass shape: {pdna_pass.shape}")

seqmap shape: (3238, 12)
screen_pass shape: (2148, 12)
pdna_pass shape: (7, 12)

In [18]:
pdna_pass

,SequenceID,ScreenID,Days,pDNABatch,Replicate,ModelID,ExcludeFromCRISPRCombined,ScreenType,Library,ModelConditionID,DrugTreated,PassesQC
2281,pDNA_batch_Avana-4,pDNA,0,Avana-4,NaN,pDNA,False,pDNA,Avana,pDNA,NaN,True
2282,pDNA_batch_Avana-3,pDNA,0,Avana-3,NaN,pDNA,False,pDNA,Avana,pDNA,NaN,True
2283,pDNA_batch_Avana-2,pDNA,0,Avana-2,NaN,pDNA,False,pDNA,Avana,pDNA,NaN,True
2348,pDNA_CD-NovaSeq_0,pDNA,0,CD-NovaSeq,NaN,pDNA,False,pDNA,Humagne-CD,pDNA,NaN,True
2349,pDNA_CD-HiSeq_0,pDNA,0,CD-HiSeq,NaN,pDNA,False,pDNA,Humagne-CD,pDNA,NaN,True
3236,pDNA_batch_KY-1,pDNA,0,KY-1,NaN,pDNA,False,pDNA,KY,pDNA,NaN,True
3237,pDNA_batch_KY-2,pDNA,0,KY-2,NaN,pDNA,False,pDNA,KY,pDNA,NaN,True

In [33]:
pdna_pass_avana = pdna_pass[pdna_pass['pDNABatch'].str.startswith('Avana', na=False)]
pdna_pass_avana

,SequenceID,ScreenID,Days,pDNABatch,Replicate,ModelID,ExcludeFromCRISPRCombined,ScreenType,Library,ModelConditionID,DrugTreated,PassesQC
2281,pDNA_batch_Avana-4,pDNA,0,Avana-4,NaN,pDNA,False,pDNA,Avana,pDNA,NaN,True
2282,pDNA_batch_Avana-3,pDNA,0,Avana-3,NaN,pDNA,False,pDNA,Avana,pDNA,NaN,True
2283,pDNA_batch_Avana-2,pDNA,0,Avana-2,NaN,pDNA,False,pDNA,Avana,pDNA,NaN,True

In [19]:
screen_pass.head()

,SequenceID,ScreenID,Days,pDNABatch,Replicate,ModelID,ExcludeFromCRISPRCombined,ScreenType,Library,ModelConditionID,DrugTreated,PassesQC
0,Colo699-311cas9-RepA-p6_Avana-4,SC-001041.AV01,21,Avana-4,A,ACH-001041,False,2DS,Avana,MC-001041-CkXW,False,True
1,Colo699-311cas9-RepB-p6_Avana-4,SC-001041.AV01,21,Avana-4,B,ACH-001041,False,2DS,Avana,MC-001041-CkXW,False,True
2,HSB-2-311cas9_RepA_p4_Avana-3,SC-001737.AV01,21,Avana-3,A,ACH-001737,False,2DS,Avana,MC-001737-6D5K,False,True
3,HSB-2-311cas9_RepB_p4_Avana-3,SC-001737.AV01,21,Avana-3,B,ACH-001737,False,2DS,Avana,MC-001737-6D5K,False,True
4,NCIH1339-311Cas9_RepA_p6_Avana-3,SC-000921.AV01,21,Avana-3,A,ACH-000921,False,2DS,Avana,MC-000921-P628,False,True

### **<span style="color:#009900;">Step 3.1 — Understand your raw readcount matrix orientation</span>**

Action
    - Confirm what is row and what is column in AvanaRawReadcounts.csv.

Hints
    - Typically: rows = sgRNAs, columns = replicates (or vice versa).
    - One column often looks like sgRNA, sgrna, guide, sequence, DepMap_ID, etc.

Code moves
    - Inspect first few rows and column names
    - Decide:
        - guide_id_col (the sgRNA identifier)
        - replicate columns = intersection of raw matrix columns with rep_map replicate IDs

Sanity checks
    - The overlap between replicate IDs in rep_good and readcount columns should be large, not like 5%.

Do column names in "raw" match rep_map['SequenceID']?

In [20]:
print(f"set results: {len(set(screen_pass['SequenceID']) & set(raw.columns))}") # SequenceIDs that exist in BOTH screen_pass and raw it is similar to A & B (See the next Cell) 
print(f"QC-passing screen SequenceIDs: {len(screen_pass['SequenceID'].unique())}")
print(f"raw columns: {len(raw.columns)}")

set results: 2148
QC-passing screen SequenceIDs: 2148
raw columns: 2285

**nol:** Columns in raw that are NOT in screen_pass. This will include:  
    – pDNA columns ✅.  
    – guide column (Unnamed: 0) ✅.  
    – any other metadata columns ✅.  
    – QC-failed replicates ✅.

In [21]:
A = set(screen_pass['SequenceID'])
B = set(raw.columns)

nol = B - A # nol = non_overlap
overlap = A & B # SequenceIDs that exist in BOTH screen_pass and raw
missing = A - B # missing = SequenceIDs that are in screen_pass but NOT in raw (Ideally len(missing) should be 0)

print(f"Non-overlapping SequenceIDs: {len(nol)}")
print(f"Overlapping SequenceIDs: {len(overlap)}")
print(f"Missing SequenceIDs: {len(missing)}")

Non-overlapping SequenceIDs: 137
Overlapping SequenceIDs: 2148
Missing SequenceIDs: 0

In [ ]:
list(nol)[:20]

In [23]:
nol_df = seqmap[
    seqmap['SequenceID'].isin(nol)
]

nol_df.head(5)

,SequenceID,ScreenID,Days,pDNABatch,Replicate,ModelID,ExcludeFromCRISPRCombined,ScreenType,Library,ModelConditionID,DrugTreated,PassesQC
90,MEG01-311cas9_RepA_p6_Avana-3,SC-000072.AV01,21,Avana-3,A,ACH-000072,False,2DS,Avana,MC-000072-l5Ss,False,False
91,MEG01-311cas9_RepB_p6_Avana-3,SC-000072.AV01,21,Avana-3,B,ACH-000072,False,2DS,Avana,MC-000072-l5Ss,False,False
103,BDCM-311Cas9_RepA_p6_Avana-3,SC-000080.AV01,21,Avana-3,A,ACH-000080,False,2DS,Avana,MC-000080-flxZ,False,False
104,BDCM-311Cas9_RepB_p6_Avana-3,SC-000080.AV01,21,Avana-3,B,ACH-000080,False,2DS,Avana,MC-000080-flxZ,False,False
141,SIGM5-311CAS9_RepA_p5_Avana-3,SC-000112.AV01,21,Avana-3,A,ACH-000112,False,2DS,Avana,MC-000112-bjRJ,False,False

In [24]:
print('Number of rows in screen_pass:', screen_pass.shape[0])
print('Number of columns in raw:', raw.shape[1])

Number of rows in screen_pass: 2148
Number of columns in raw: 2285

### **<span style="color:#009900;">Step 3.2 — Create a “screen counts” matrix and a “pDNA counts” matrix</span>**

**Action:**  
Split the raw matrix into two views:     
– counts for QC-passing screen replicates  
– counts for pDNA replicates (grouped by pDNA batch)   

**Hints:**  
– Use your replicate lists from screen_pass and pdna_pass     
– This is where you avoid mixing baselines and screens by accident     

**Code moves:**
– screen_cols = list(screen_pass[replicate_id_col])     
– pdna_cols = list(pdna_pass[replicate_id_col])    
– Subset the raw dataframe to those columns (+ guide id)   

**Sanity checks:**    
– No missing replicate columns (if some are missing, print which ones are missing — it will tell you if naming differs)

In [28]:
screen_seqids_pass = screen_pass['SequenceID'].unique()
len(screen_seqids_pass)
screen_seqids_pass

array(['Colo699-311cas9-RepA-p6_Avana-4',
       'Colo699-311cas9-RepB-p6_Avana-4', 'HSB-2-311cas9_RepA_p4_Avana-3',
       ..., 'UPMM3-311cas9-RepA-p4_Avana-4',
       'UACC3199-311cas9-RepA-p4_Avana-4',
       'UACC3199-311cas9-RepB-p4_Avana-4'], shape=(2148,), dtype=object)

In [30]:
raw_screen_pass = raw[['sgRNA_seq'] + list(screen_seqids_pass)]
raw_screen_pass.head()

,sgRNA_seq,Colo699-311cas9-RepA-p6_Avana-4,Colo699-311cas9-RepB-p6_Avana-4,HSB-2-311cas9_RepA_p4_Avana-3,HSB-2-311cas9_RepB_p4_Avana-3,NCIH1339-311Cas9_RepA_p6_Avana-3,NCIH1339-311Cas9_RepB_p6_Avana-3,HEL-311Cas9_RepA_p4_Avana-3,HEL-311Cas9_RepB_p4_Avana-3,HEL9217-311Cas9_RepA_p6_Avana-3,...,SCCH196-311Cas9-RepB-P6_Avana-4,SNU977-311Cas9-AVANA-RepA-p6_Avana-4,SNU977-311Cas9-AVANA-RepB-p6_Avana-4,HMMME-311cas9-RepA-p6_Avana-4,HMMME-311cas9-RepB-p6_Avana-4,UACC3133-311Cas9-RepB-P6_Avana-4,LU139-311cas9-RepB-p5_Avana-4,UPMM3-311cas9-RepA-p4_Avana-4,UACC3199-311cas9-RepA-p4_Avana-4,UACC3199-311cas9-RepB-p4_Avana-4
0,AAAAAAATCCAGCAATGCAG,463.0,521.0,514.0,776.0,474.0,329.0,214.0,254.0,510.0,...,411.0,246.0,287.0,366.0,450.0,460.0,419.0,275.0,528.0,546.0
1,AAAAAACCCGTAGATAGCCT,570.0,596.0,581.0,756.0,398.0,281.0,218.0,270.0,603.0,...,715.0,325.0,485.0,884.0,741.0,406.0,577.0,385.0,733.0,608.0
2,AAAAAAGAAGAAAAAACCAG,93.0,79.0,135.0,244.0,85.0,45.0,106.0,118.0,171.0,...,90.0,42.0,110.0,49.0,52.0,171.0,45.0,100.0,149.0,127.0
3,AAAAAAGCTCAAGAAGGAGG,168.0,150.0,153.0,268.0,134.0,161.0,69.0,105.0,258.0,...,172.0,99.0,148.0,270.0,205.0,209.0,99.0,101.0,217.0,181.0
4,AAAAAAGGCTGTAAAAGCGT,197.0,264.0,276.0,270.0,245.0,129.0,181.0,120.0,345.0,...,223.0,92.0,214.0,325.0,352.0,267.0,197.0,206.0,379.0,347.0

In [27]:
type(sequenceids_pass)

numpy.ndarray

In [34]:
pdna_seqids_pass = pdna_pass_avana['SequenceID'].unique()
len(pdna_seqids_pass)
pdna_seqids_pass

array(['pDNA_batch_Avana-4', 'pDNA_batch_Avana-3', 'pDNA_batch_Avana-2'],
      dtype=object)

In [36]:
raw_pdna_avana_pass = raw[['sgRNA_seq'] + list(pdna_seqids_pass)]
raw_pdna_avana_pass.head()

,sgRNA_seq,pDNA_batch_Avana-4,pDNA_batch_Avana-3,pDNA_batch_Avana-2
0,AAAAAAATCCAGCAATGCAG,2165.0,6327.0,190.5
1,AAAAAACCCGTAGATAGCCT,3127.5,9322.0,289.0
2,AAAAAAGAAGAAAAAACCAG,517.0,2030.5,41.5
3,AAAAAAGCTCAAGAAGGAGG,918.0,3333.5,82.5
4,AAAAAAGGCTGTAAAAGCGT,1184.0,4038.0,117.5

In [ ]:
screen_pass.to_csv(os.path.expanduser("~/Library/CloudStorage/GoogleDrive-nima.fakouri@gmail.com/My Drive/informatics/AI projects/crispr_ai_ml/data/processed/phase3_inputs/screen_metadata_pass.csv"), index=False)
pdna_pass.to_csv(os.path.expanduser("~/Library/CloudStorage/GoogleDrive-nima.fakouri@gmail.com/My Drive/informatics/AI projects/crispr_ai_ml/data/processed/phase3_inputs/pdna_metadata_all.csv"), index=False)
pdna_pass_avana.to_csv(os.path.expanduser("~/Library/CloudStorage/GoogleDrive-nima.fakouri@gmail.com/My Drive/informatics/AI projects/crispr_ai_ml/data/processed/phase3_inputs/pdna_metadata_avana.csv"), index=False)
raw_screen_pass.to_csv(os.path.expanduser("~/Library/CloudStorage/GoogleDrive-nima.fakouri@gmail.com/My Drive/informatics/AI projects/crispr_ai_ml/data/processed/phase3_inputs/raw_screen_counts_pass.csv"), index=False)
raw_pdna_avana_pass.to_csv(os.path.expanduser("~/Library/CloudStorage/GoogleDrive-nima.fakouri@gmail.com/My Drive/informatics/AI projects/crispr_ai_ml/data/processed/phase3_inputs/raw_pdna_avana_counts_pass.csv"), index=False)